[mypy]
python_version = 3.13
warn_unused_configs = True
ignore_missing_imports = True
disallow_untyped_defs = False
exclude = migrations|__pycache__|tests.py

[mypy-django.*]
ignore_missing_imports = True

[tool.mypy]
plugins = mypy_django_plugin.main

[tool.django-stubs]
django_settings_module = "IS_Django.settings"

[mypy-catalog.models.*]
disallow_untyped_defs = False

[mypy-blog.models.*]
disallow_untyped_defs = False